# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=1234

# H2 DB 설정
spring.datasource.url=jdbc:h2:mem:ohtdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 웹 콘솔 활성화 (이게 핵심입니다!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
